### ISSUE TITLE
Erreur en suivant le README pour installer et lancer l'application en local

### ISSUE THREAD

**Issue by Vladou73** [betagouv/urbanvitaliz-django#79]
Bonjour,

J'ai suivi le tuto dans le README pour installer localement l'application mais je n'ai pas réussi à aller jusqu'au bout, est-ce que vous pourriez m'aider svp ?

Lorsque je run `docker-compose up` les conteneurs sont bien créés mais dans les logs du conteneur de la DB j'ai une erreur qui apparait

```
2022-10-28 16:00:45.807 UTC [1] LOG:  database system is ready to accept connections
2022-10-28 16:05:00.774 UTC [71] ERROR:  relation "django_content_type" does not exist at character 106
2022-10-28 16:05:00.774 UTC [71] STATEMENT:  SELECT "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_content_type" WHERE ("django_content_type"."app_label" = 'projects' AND "django_content_type"."model" = 'project') LIMIT 21
```

Elle est non bloquante mais une fois arrivé à l'étape `./manage.py migrate`, après avoir export une `SECRET_KEY` dans mon environnement et ajouté le fichier development.py modifié comme demandé, je retrouve la même erreur qui bloque la migration

```
root ➜ /workspace $ ./manage.py migrate
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.errors.UndefinedTable: relation "django_content_type" does not exist
LINE 1: ..."."app_label", "django_content_type"."model" FROM "django_co...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/workspace/./manage.py", line 22, in <module>
    main()
  File "/workspace/./manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.11/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.11/site-packages/django/core/management/__init__.py", line 395, in execute
    django.setup()
  File "/usr/local/lib/python3.11/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.11/site-packages/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "/usr/local/lib/python3.11/site-packages/django/apps/config.py", line 301, in import_models
    self.models_module = import_module(models_module_name)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/workspace/urbanvitaliz/apps/crm/models.py", line 90, in <module>
    project_ct = ContentType.objects.get_for_model(projects_models.Project)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/contrib/contenttypes/models.py", line 51, in get_for_model
    ct = self.get(app_label=opts.app_label, model=opts.model_name)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 431, in get
    num = len(clone)
          ^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 262, in __len__
    self._fetch_all()
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1324, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 51, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/sql/compiler.py", line 1175, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 98, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 79, in _execute
    with self.db.wrap_database_errors:
  File "/usr/local/lib/python3.11/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.ProgrammingError: relation "django_content_type" does not exist
LINE 1: ..."."app_label", "django_content_type"."model" FROM "django_co...

**Comment by glibersat** [comment]
Bonjour @Vladou73 , ce devrait être corrigé dans main normalement, peux tu m'indiquer si c'est bon pour toi ?
Merci !

**Comment by glibersat** [comment]
Est-ce que tu as bien mis le site en DEBUG = True en recopiant le fichier development.py.example ?

**Comment by Vladou73** [comment]
yes c'est bien en `DEBUG = True` je te mets ci-dessous le fichier en entier.
Je viens de modifier cette ligne `SILENCED_SYSTEM_CHECKS = ['captcha.recaptcha_test_key_error', "sites.E101"]` et j'ai l'impression que ça a bien fonctionné pour que l'erreur ne remonte plus.

- Du coup je suis allé au bout de l'étape de migration de la DB 👍 
- Ensuite l'étape `cd urbanvitaliz/frontend && yarn dev`  c'est bon aussi
- Et par contre pour lancer le serveur, je suis obligé d'ouvrir un nouveau terminal et refaire `docker-compose up` avant de lancer le serveur avec la commande `./manage.py runserver` non ? C'est ce que j'ai fait, le serveur se lance donc j'ai bien le serveur et le client qui sont lancés mais quand j'essaie d'y accéder sur http://localhost:8000/ la connexion échoue, il doit y avoir un truc que je fais mal à un moment :/

Mais ça avance :D


development.py
```python
# encoding: utf-8

"""
Settings for development

author  : raphael.marvie@beta.gouv.fr,guillaume.libersat@beta.gouv.fr
created : 2021-05-31 11:54:53 CEST
"""

from .common import *

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    "localhost",
]

INSTALLED_APPS += ("debug_toolbar",)

MIDDLEWARE += ("debug_toolbar.middleware.DebugToolbarMiddleware",)

# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
     'default': {
         'ENGINE': 'django.db.backends.postgresql',
         'NAME': os.environ.get('POSTGRES_NAME'),
         'USER': os.environ.get('POSTGRES_USER'),
         'PASSWORD': os.environ.get('POSTGRES_PASSWORD'),
         'HOST': 'db',
         'PORT': 5432,
     }
}

# EMAIL
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# SECRET_KEY = os.environ.get('SECRET_KEY')
SECRET_KEY = "SECRET_KEY"

SENDINBLUE_API_KEY = os.environ.get('SENDINBLUE_API_KEY')
SENDINBLUE_FORCE_DEBUG = True

# Recpatcha

SILENCED_SYSTEM_CHECKS = ['captcha.recaptcha_test_key_error', "sites.E101"]
RECAPTCHA_REQUIRED_SCORE = 0

# eof
```

**Comment by Vladou73** [comment]
Hello @glibersat , est-ce que ce serait possible de se caler un point ensemble pour voir ensemble le lancement de l'app en local via docker stp ? éventuellement la semaine pro ou celle d'après ?

**Comment by glibersat** [comment]
Salut! Oui, sans problème, lundi, vers 14H?

**Comment by Vladou73** [comment]
lundi à 14h je pourrai pas, soit avant (fin matinée ou 13h) ou bien après 16h, est-ce que ça pourrait matcher ?

**Comment by glibersat** [comment]
Ok pour 16H!
